Fix `perfect_odometry` rosbag
Ekumen-OS/beluga pull request #238
Opened 2023-07-01 22:52 UTC by nahueespinosa

### Proposed changes

Fixes #232.

This patch fixes message timestamps in the rosbag to match the starting simulation time.

* The contents of the messages were not altered.
* The storage backend was changed to mcap
* The last messages where there was a collision against one of the walls were deleted.

#### Type of change

- [x] 🐛 Bugfix (change which fixes an issue)
- [ ] 🚀 Feature (change which adds functionality)
- [ ] 📚 Documentation (change which fixes or extends documentation)

### Checklist

- [x] Lint and unit tests (if any) pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)
- [x] All commits have been signed for [DCO](https://developercertificate.org/)

2023-07-03 15:23 UTC, glpuga requested changes
The topics LGTM, but when I tried to run the perfect odometry example rosbag does not start because the MCAP plugin is not installed.

After installing manually ros-humble-rosbag2-storage-mcap it worked just fine. We are probably missing a dependency declaration. 

I had started the docker with `./run --build` .

2023-07-03 17:57 UTC, nahueespinosa commented
@glpuga Good catch! I originally tested on Rolling.

I reverted to using sqlite3 instead of mcap so no need to add extra dependencies.

2023-07-09 20:26 UTC, glpuga commented
I looked into the results of the `beluga_benchmark` that run on top of this. The data gathered looks good and can be plotted just fine for `beluga_amcl`, but `nav2_amcl` seems to be crashing right after starting. 

This can be duplicated by running:

```
colcon build 
source install/setup.bash
cd src/beluga/beluga_benchmark/docs/reports/2023-06-03
mkdir test
cd test
ros2 run beluga_benchmark parameterized_run 250 300 400 500 750 1000 2000 5000 10000 20000 50000 100000 200000 --params-file ../beam_params.yaml --package nav2_amcl --executable amcl
cd -
``` 

Nothing is left on the logs to indicate why `nav2_amcl` is giving up.

2023-07-10 13:15 UTC, nahueespinosa commented
@glpuga I can reproduce the error in Humble, but everything works fine in Rolling. More investigation is needed.

2023-07-10 23:57 UTC, nahueespinosa commented
@glpuga I think the failure is most likely related to what @ivanpauno found here: https://github.com/Ekumen-OS/beluga/pull/117#issuecomment-1442370024

I don't know how we ended up re-enabling `recovery_alpha_fast` and `recovery_alpha_slow` for benchmarks, and how that worked in the past, but we have two alternatives:
- Benchmark using Rolling where the `nav2_amcl` bug was fixed.
- Benchmark with adaptive recovery disabled.

Any of those options is unrelated to this PR.

2023-07-11 12:47 UTC, glpuga approved these changes

2023-07-11 12:59 UTC, merged