Reduce duplication when using `yaml-cpp`
Ekumen-OS/beluga pull request #383
Opened 2024-05-23 11:52 UTC by nahueespinosa

### Proposed changes

Minor changes to the tutorial code to reduce duplication.

#### Type of change

- [ ] 🐛 Bugfix (change which fixes an issue)
- [x] 🚀 Feature (change which adds functionality)
- [ ] 📚 Documentation (change which fixes or extends documentation)

### Checklist

- [x] Lint and unit tests (if any) pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)
- [x] All commits have been signed for [DCO](https://developercertificate.org/)

2024-05-23 17:28 UTC, hidmic approved these changes
Looks awesome to me. Nothing to add. I haven't tried it though. @Alondruck thoughts?

2024-05-24 12:37 UTC, nahueespinosa commented
@Alondruck Have you had a chance to test this with the post-processing code?

2024-05-24 12:48 UTC, Alondruck commented
> @Alondruck Have you had a chance to test this with the post-processing code?

Yes @nahueespinosa, because that I left you the comment to not initialize the vector with default values, I test the post-processing with the solution that I suggested to you and in that way it works.

2024-05-24 12:51 UTC, nahueespinosa commented
@Alondruck You may need to submit your review. I think your comments might be in draft yet since I can't see them.

2024-05-24 13:09 UTC, Alondruck requested changes

2024-05-24 13:54 UTC, nahueespinosa commented on beluga_tutorial/src/main.cpp
> +  std::vector<RobotRecord> records{parameters.number_of_cycles};
Good catch! I mean to write https://github.com/Ekumen-OS/beluga/pull/383/commits/7f3523be5ea3f675f62f0d6c161805d46fd1ba3c :sweat_smile:

2024-05-24 13:55 UTC, nahueespinosa commented on beluga_tutorial/package.xml
> +  <version>2.0.0</version>
All packages in the repo need to have the same version.

2024-05-24 16:21 UTC, Alondruck approved these changes
LGTM!

2024-05-24 16:28 UTC, merged